// Generated by gencpp from file uav_messages/EsdfQuery.msg
// DO NOT EDIT!


#ifndef UAV_MESSAGES_MESSAGE_ESDFQUERY_H
#define UAV_MESSAGES_MESSAGE_ESDFQUERY_H

#include <ros/service_traits.h>


#include <uav_messages/EsdfQueryRequest.h>
#include <uav_messages/EsdfQueryResponse.h>


namespace uav_messages
{

struct EsdfQuery
{

typedef EsdfQueryRequest Request;
typedef EsdfQueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EsdfQuery
} // namespace uav_messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_messages::EsdfQuery > {
  static const char* value()
  {
    return "877c5238469713853bdc6a19780c7540";
  }

  static const char* value(const ::uav_messages::EsdfQuery&) { return value(); }
};

template<>
struct DataType< ::uav_messages::EsdfQuery > {
  static const char* value()
  {
    return "uav_messages/EsdfQuery";
  }

  static const char* value(const ::uav_messages::EsdfQuery&) { return value(); }
};


// service_traits::MD5Sum< ::uav_messages::EsdfQueryRequest> should match
// service_traits::MD5Sum< ::uav_messages::EsdfQuery >
template<>
struct MD5Sum< ::uav_messages::EsdfQueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_messages::EsdfQuery >::value();
  }
  static const char* value(const ::uav_messages::EsdfQueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_messages::EsdfQueryRequest> should match
// service_traits::DataType< ::uav_messages::EsdfQuery >
template<>
struct DataType< ::uav_messages::EsdfQueryRequest>
{
  static const char* value()
  {
    return DataType< ::uav_messages::EsdfQuery >::value();
  }
  static const char* value(const ::uav_messages::EsdfQueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_messages::EsdfQueryResponse> should match
// service_traits::MD5Sum< ::uav_messages::EsdfQuery >
template<>
struct MD5Sum< ::uav_messages::EsdfQueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_messages::EsdfQuery >::value();
  }
  static const char* value(const ::uav_messages::EsdfQueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_messages::EsdfQueryResponse> should match
// service_traits::DataType< ::uav_messages::EsdfQuery >
template<>
struct DataType< ::uav_messages::EsdfQueryResponse>
{
  static const char* value()
  {
    return DataType< ::uav_messages::EsdfQuery >::value();
  }
  static const char* value(const ::uav_messages::EsdfQueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_MESSAGES_MESSAGE_ESDFQUERY_H
