// Generated by gencpp from file uav_messages/EsdfQueryResponse.msg
// DO NOT EDIT!


#ifndef UAV_MESSAGES_MESSAGE_ESDFQUERYRESPONSE_H
#define UAV_MESSAGES_MESSAGE_ESDFQUERYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_messages
{
template <class ContainerAllocator>
struct EsdfQueryResponse_
{
  typedef EsdfQueryResponse_<ContainerAllocator> Type;

  EsdfQueryResponse_()
    : distance(0.0)  {
    }
  EsdfQueryResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EsdfQueryResponse_

typedef ::uav_messages::EsdfQueryResponse_<std::allocator<void> > EsdfQueryResponse;

typedef boost::shared_ptr< ::uav_messages::EsdfQueryResponse > EsdfQueryResponsePtr;
typedef boost::shared_ptr< ::uav_messages::EsdfQueryResponse const> EsdfQueryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_messages::EsdfQueryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_messages::EsdfQueryResponse_<ContainerAllocator1> & lhs, const ::uav_messages::EsdfQueryResponse_<ContainerAllocator2> & rhs)
{
  return lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_messages::EsdfQueryResponse_<ContainerAllocator1> & lhs, const ::uav_messages::EsdfQueryResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acff7fda0c683c872875f5c4b069f124";
  }

  static const char* value(const ::uav_messages::EsdfQueryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacff7fda0c683c87ULL;
  static const uint64_t static_value2 = 0x2875f5c4b069f124ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_messages/EsdfQueryResponse";
  }

  static const char* value(const ::uav_messages::EsdfQueryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance\n"
;
  }

  static const char* value(const ::uav_messages::EsdfQueryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EsdfQueryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_messages::EsdfQueryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_messages::EsdfQueryResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGES_MESSAGE_ESDFQUERYRESPONSE_H
