// Generated by gencpp from file uav_messages/EsdfQueryRequest.msg
// DO NOT EDIT!


#ifndef UAV_MESSAGES_MESSAGE_ESDFQUERYREQUEST_H
#define UAV_MESSAGES_MESSAGE_ESDFQUERYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_messages
{
template <class ContainerAllocator>
struct EsdfQueryRequest_
{
  typedef EsdfQueryRequest_<ContainerAllocator> Type;

  EsdfQueryRequest_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  EsdfQueryRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EsdfQueryRequest_

typedef ::uav_messages::EsdfQueryRequest_<std::allocator<void> > EsdfQueryRequest;

typedef boost::shared_ptr< ::uav_messages::EsdfQueryRequest > EsdfQueryRequestPtr;
typedef boost::shared_ptr< ::uav_messages::EsdfQueryRequest const> EsdfQueryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_messages::EsdfQueryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_messages::EsdfQueryRequest_<ContainerAllocator1> & lhs, const ::uav_messages::EsdfQueryRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_messages::EsdfQueryRequest_<ContainerAllocator1> & lhs, const ::uav_messages::EsdfQueryRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const ::uav_messages::EsdfQueryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_messages/EsdfQueryRequest";
  }

  static const char* value(const ::uav_messages::EsdfQueryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::uav_messages::EsdfQueryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EsdfQueryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_messages::EsdfQueryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_messages::EsdfQueryRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGES_MESSAGE_ESDFQUERYREQUEST_H
