// Generated by gencpp from file uav_messages/Heartbeat.msg
// DO NOT EDIT!


#ifndef UAV_MESSAGES_MESSAGE_HEARTBEAT_H
#define UAV_MESSAGES_MESSAGE_HEARTBEAT_H

#include <ros/service_traits.h>


#include <uav_messages/HeartbeatRequest.h>
#include <uav_messages/HeartbeatResponse.h>


namespace uav_messages
{

struct Heartbeat
{

typedef HeartbeatRequest Request;
typedef HeartbeatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Heartbeat
} // namespace uav_messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_messages::Heartbeat > {
  static const char* value()
  {
    return "927048d99b53abc440d02d20ffdd561a";
  }

  static const char* value(const ::uav_messages::Heartbeat&) { return value(); }
};

template<>
struct DataType< ::uav_messages::Heartbeat > {
  static const char* value()
  {
    return "uav_messages/Heartbeat";
  }

  static const char* value(const ::uav_messages::Heartbeat&) { return value(); }
};


// service_traits::MD5Sum< ::uav_messages::HeartbeatRequest> should match
// service_traits::MD5Sum< ::uav_messages::Heartbeat >
template<>
struct MD5Sum< ::uav_messages::HeartbeatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_messages::Heartbeat >::value();
  }
  static const char* value(const ::uav_messages::HeartbeatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_messages::HeartbeatRequest> should match
// service_traits::DataType< ::uav_messages::Heartbeat >
template<>
struct DataType< ::uav_messages::HeartbeatRequest>
{
  static const char* value()
  {
    return DataType< ::uav_messages::Heartbeat >::value();
  }
  static const char* value(const ::uav_messages::HeartbeatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_messages::HeartbeatResponse> should match
// service_traits::MD5Sum< ::uav_messages::Heartbeat >
template<>
struct MD5Sum< ::uav_messages::HeartbeatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_messages::Heartbeat >::value();
  }
  static const char* value(const ::uav_messages::HeartbeatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_messages::HeartbeatResponse> should match
// service_traits::DataType< ::uav_messages::Heartbeat >
template<>
struct DataType< ::uav_messages::HeartbeatResponse>
{
  static const char* value()
  {
    return DataType< ::uav_messages::Heartbeat >::value();
  }
  static const char* value(const ::uav_messages::HeartbeatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_MESSAGES_MESSAGE_HEARTBEAT_H
