// Generated by gencpp from file uav_messages/HeartbeatRequest.msg
// DO NOT EDIT!


#ifndef UAV_MESSAGES_MESSAGE_HEARTBEATREQUEST_H
#define UAV_MESSAGES_MESSAGE_HEARTBEATREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_messages
{
template <class ContainerAllocator>
struct HeartbeatRequest_
{
  typedef HeartbeatRequest_<ContainerAllocator> Type;

  HeartbeatRequest_()
    : heartbeat(false)  {
    }
  HeartbeatRequest_(const ContainerAllocator& _alloc)
    : heartbeat(false)  {
  (void)_alloc;
    }



   typedef uint8_t _heartbeat_type;
  _heartbeat_type heartbeat;





  typedef boost::shared_ptr< ::uav_messages::HeartbeatRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_messages::HeartbeatRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HeartbeatRequest_

typedef ::uav_messages::HeartbeatRequest_<std::allocator<void> > HeartbeatRequest;

typedef boost::shared_ptr< ::uav_messages::HeartbeatRequest > HeartbeatRequestPtr;
typedef boost::shared_ptr< ::uav_messages::HeartbeatRequest const> HeartbeatRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_messages::HeartbeatRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_messages::HeartbeatRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_messages::HeartbeatRequest_<ContainerAllocator1> & lhs, const ::uav_messages::HeartbeatRequest_<ContainerAllocator2> & rhs)
{
  return lhs.heartbeat == rhs.heartbeat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_messages::HeartbeatRequest_<ContainerAllocator1> & lhs, const ::uav_messages::HeartbeatRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_messages::HeartbeatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_messages::HeartbeatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_messages::HeartbeatRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_messages::HeartbeatRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_messages::HeartbeatRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_messages::HeartbeatRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_messages::HeartbeatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "200e4430827ea87384fb21872bb9ff37";
  }

  static const char* value(const ::uav_messages::HeartbeatRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x200e4430827ea873ULL;
  static const uint64_t static_value2 = 0x84fb21872bb9ff37ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_messages::HeartbeatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_messages/HeartbeatRequest";
  }

  static const char* value(const ::uav_messages::HeartbeatRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_messages::HeartbeatRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool heartbeat\n"
;
  }

  static const char* value(const ::uav_messages::HeartbeatRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_messages::HeartbeatRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heartbeat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeartbeatRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_messages::HeartbeatRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_messages::HeartbeatRequest_<ContainerAllocator>& v)
  {
    s << indent << "heartbeat: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.heartbeat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGES_MESSAGE_HEARTBEATREQUEST_H
