// Generated by gencpp from file uav_messages/HeightRequest.msg
// DO NOT EDIT!


#ifndef UAV_MESSAGES_MESSAGE_HEIGHTREQUEST_H
#define UAV_MESSAGES_MESSAGE_HEIGHTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>

namespace uav_messages
{
template <class ContainerAllocator>
struct HeightRequest_
{
  typedef HeightRequest_<ContainerAllocator> Type;

  HeightRequest_()
    : points()  {
    }
  HeightRequest_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _points_type;
  _points_type points;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(OK)
  #undef OK
#endif
#if defined(_WIN32) && defined(SOME_INVALID)
  #undef SOME_INVALID
#endif

  enum {
    OK = 0u,
    SOME_INVALID = 1u,
  };


  typedef boost::shared_ptr< ::uav_messages::HeightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_messages::HeightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HeightRequest_

typedef ::uav_messages::HeightRequest_<std::allocator<void> > HeightRequest;

typedef boost::shared_ptr< ::uav_messages::HeightRequest > HeightRequestPtr;
typedef boost::shared_ptr< ::uav_messages::HeightRequest const> HeightRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_messages::HeightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_messages::HeightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_messages::HeightRequest_<ContainerAllocator1> & lhs, const ::uav_messages::HeightRequest_<ContainerAllocator2> & rhs)
{
  return lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_messages::HeightRequest_<ContainerAllocator1> & lhs, const ::uav_messages::HeightRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_messages::HeightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_messages::HeightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_messages::HeightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_messages::HeightRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_messages::HeightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_messages::HeightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_messages::HeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "002b2b2002a67e6ccbeb90a7022827a5";
  }

  static const char* value(const ::uav_messages::HeightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x002b2b2002a67e6cULL;
  static const uint64_t static_value2 = 0xcbeb90a7022827a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_messages::HeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_messages/HeightRequest";
  }

  static const char* value(const ::uav_messages::HeightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_messages::HeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 OK=0\n"
"uint8 SOME_INVALID=1\n"
"\n"
"geometry_msgs/Vector3[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::uav_messages::HeightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_messages::HeightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_messages::HeightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_messages::HeightRequest_<ContainerAllocator>& v)
  {
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_MESSAGES_MESSAGE_HEIGHTREQUEST_H
