// Generated by gencpp from file uav_messages/Height.msg
// DO NOT EDIT!


#ifndef UAV_MESSAGES_MESSAGE_HEIGHT_H
#define UAV_MESSAGES_MESSAGE_HEIGHT_H

#include <ros/service_traits.h>


#include <uav_messages/HeightRequest.h>
#include <uav_messages/HeightResponse.h>


namespace uav_messages
{

struct Height
{

typedef HeightRequest Request;
typedef HeightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Height
} // namespace uav_messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_messages::Height > {
  static const char* value()
  {
    return "af6c894dddf3f73449d8d258ec820c83";
  }

  static const char* value(const ::uav_messages::Height&) { return value(); }
};

template<>
struct DataType< ::uav_messages::Height > {
  static const char* value()
  {
    return "uav_messages/Height";
  }

  static const char* value(const ::uav_messages::Height&) { return value(); }
};


// service_traits::MD5Sum< ::uav_messages::HeightRequest> should match
// service_traits::MD5Sum< ::uav_messages::Height >
template<>
struct MD5Sum< ::uav_messages::HeightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_messages::Height >::value();
  }
  static const char* value(const ::uav_messages::HeightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_messages::HeightRequest> should match
// service_traits::DataType< ::uav_messages::Height >
template<>
struct DataType< ::uav_messages::HeightRequest>
{
  static const char* value()
  {
    return DataType< ::uav_messages::Height >::value();
  }
  static const char* value(const ::uav_messages::HeightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_messages::HeightResponse> should match
// service_traits::MD5Sum< ::uav_messages::Height >
template<>
struct MD5Sum< ::uav_messages::HeightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_messages::Height >::value();
  }
  static const char* value(const ::uav_messages::HeightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_messages::HeightResponse> should match
// service_traits::DataType< ::uav_messages::Height >
template<>
struct DataType< ::uav_messages::HeightResponse>
{
  static const char* value()
  {
    return DataType< ::uav_messages::Height >::value();
  }
  static const char* value(const ::uav_messages::HeightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_MESSAGES_MESSAGE_HEIGHT_H
