# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uav_messages/GroundClothPoints.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class GroundClothPoints(genpy.Message):
  _md5sum = "38fbc55ea331f440db17b20331203f67"
  _type = "uav_messages/GroundClothPoints"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Data alignment origin
geometry_msgs/Vector3 origin
uint32 width
uint32 length
float64 resolution
float64[] heights
================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['origin','width','length','resolution','heights']
  _slot_types = ['geometry_msgs/Vector3','uint32','uint32','float64','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       origin,width,length,resolution,heights

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GroundClothPoints, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.origin is None:
        self.origin = geometry_msgs.msg.Vector3()
      if self.width is None:
        self.width = 0
      if self.length is None:
        self.length = 0
      if self.resolution is None:
        self.resolution = 0.
      if self.heights is None:
        self.heights = []
    else:
      self.origin = geometry_msgs.msg.Vector3()
      self.width = 0
      self.length = 0
      self.resolution = 0.
      self.heights = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d2Id().pack(_x.origin.x, _x.origin.y, _x.origin.z, _x.width, _x.length, _x.resolution))
      length = len(self.heights)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.heights))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.origin is None:
        self.origin = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.origin.x, _x.origin.y, _x.origin.z, _x.width, _x.length, _x.resolution,) = _get_struct_3d2Id().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.heights = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d2Id().pack(_x.origin.x, _x.origin.y, _x.origin.z, _x.width, _x.length, _x.resolution))
      length = len(self.heights)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.heights.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.origin is None:
        self.origin = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 40
      (_x.origin.x, _x.origin.y, _x.origin.z, _x.width, _x.length, _x.resolution,) = _get_struct_3d2Id().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.heights = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d2Id = None
def _get_struct_3d2Id():
    global _struct_3d2Id
    if _struct_3d2Id is None:
        _struct_3d2Id = struct.Struct("<3d2Id")
    return _struct_3d2Id
